---
- name: Create users
  hosts: all
  become: true
  vars_files:
    - users.yml
  
  tasks:
    - name: Add users
      user:
        name: "{{ item.value.username }}"
        comment: "{{ item.value.comment }}"
        create_home: yes
        home: "{{ item.value.homedir }}"
        password: "{{ item.value.password | password_hash('sha512') }}"
        update_password: on_create
        # state: absent
      loop: "{{ users | dict2items }}"
      loop_control:
          label: "{{ item.key }}"

    # - name: print the secure variable
    #   # no_log: yes
    #   debug:
    #     msg:
    #       - "user: {{ item.value.username }}; homedir: {{ item.value.homedir }}; comment: {{ item.value.comment }}; "
    #       - "password: {{ item.value.password | password_hash('sha512') }}"
    #   loop: "{{ users | dict2items }}"
    #   loop_control:
    #     label: "{{ item.key }}"
...
