---
# tasks file for apache_install
- name: Install httpd
  yum:
    name: httpd
    state: latest

- name: Start service httpd, if not started
  service:
    name: httpd
    state: started
    enabled: yes

- name: Create index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0644'
  notify: restart httpd

- name: firewalld configuration
  firewalld:
    zone: public
    service: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - https
    - http
